

import java.util.Scanner;
import java.util.Random;

public class Number_Guessing_Game {
    // Generate RANDOM guess
    static int generateGuess(int low, int high, Random rand) {
        return rand.nextInt(high - low + 1) + low;//in this line we generate random number
    }

    // Get user feedback
    static String getFeedback(Scanner sc) {
        System.out.print("Enter feedback (high / low / correct): ");
        return sc.nextLine().toLowerCase();
    }

    // Update range based on feedback
    static int[] updateRange(String feedback, int guess, int low, int high) {
        if (feedback.equals("high")) {
            high = guess - 1;
        } else if (feedback.equals("low")) {
            low = guess + 1;
        }
        return new int[]{low, high};
    }

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        Random rand = new Random();

        int low = 1;
        int high = 100;
        boolean correct = false;

        System.out.println("Think of a number between 1 and 100.");

        while (!correct && low <= high) {

            int guess = generateGuess(low, high, rand);
            System.out.println("My guess is: " + guess);//huess generated by guess method

            String feedback = getFeedback(sc);

            if (feedback.equals("correct")) {
                System.out.println("I guessed it right!");
                correct = true;
            } else {
                int[] range = updateRange(feedback, guess, low, high);
                low = range[0];
                high = range[1];
            }
        }
    }
}
